// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sedziowanie.Data;

#nullable disable

namespace Sedziowanie.Migrations
{
    [DbContext(typeof(DBObsadyContext))]
    [Migration("20260422143019_AddMustChangePassword")]
    partial class AddMustChangePassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sedziowanie.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SedziaId")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SedziaId")
                        .IsUnique()
                        .HasFilter("[SedziaId] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Sedziowanie.Models.Komisja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Komisje");
                });

            modelBuilder.Entity("Sedziowanie.Models.KomisjaCzlonek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Funkcja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KomisjaId")
                        .HasColumnType("int");

                    b.Property<int>("SedziaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KomisjaId");

                    b.HasIndex("SedziaId");

                    b.ToTable("KomisjaCzlonkowie");
                });

            modelBuilder.Entity("Sedziowanie.Models.Mecz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("DodatkoweInformacje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gosc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoscKlubId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gospodarz")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GospodarzKlubId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumerMeczu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RozgrywkiId")
                        .HasColumnType("int");

                    b.Property<int?>("SedziaGlownyId")
                        .HasColumnType("int");

                    b.Property<int?>("SedziaIIId")
                        .HasColumnType("int");

                    b.Property<int?>("SedziaIId")
                        .HasColumnType("int");

                    b.Property<int?>("SedziaLiniowyIIId")
                        .HasColumnType("int");

                    b.Property<int?>("SedziaLiniowyIId")
                        .HasColumnType("int");

                    b.Property<int?>("SedziaSekretarzId")
                        .HasColumnType("int");

                    b.Property<string>("Turniej")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("UdostepnijGodzine")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GoscKlubId");

                    b.HasIndex("GospodarzKlubId");

                    b.HasIndex("RozgrywkiId");

                    b.HasIndex("SedziaGlownyId");

                    b.HasIndex("SedziaIIId");

                    b.HasIndex("SedziaIId");

                    b.HasIndex("SedziaLiniowyIIId");

                    b.HasIndex("SedziaLiniowyIId");

                    b.HasIndex("SedziaSekretarzId");

                    b.ToTable("Mecze");
                });

            modelBuilder.Entity("Sedziowanie.Models.Niedyspozycja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Koniec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Poczatek")
                        .HasColumnType("datetime2");

                    b.Property<int>("SedziaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SedziaId");

                    b.ToTable("Niedyspozycje");
                });

            modelBuilder.Entity("Sedziowanie.Models.Rozgrywki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rozgrywki");
                });

            modelBuilder.Entity("Sedziowanie.Models.Sedzia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyUrlop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Klasa")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Miasto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Sedziowie");
                });

            modelBuilder.Entity("Sedziowanie.Models.SukcesWydzialu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Osiagniecie")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Sklad")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Zawody")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("SukcesyWydzialu");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sedziowanie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sedziowanie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sedziowanie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sedziowanie.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sedziowanie.Models.ApplicationUser", b =>
                {
                    b.HasOne("Sedziowanie.Models.Sedzia", "Sedzia")
                        .WithOne()
                        .HasForeignKey("Sedziowanie.Models.ApplicationUser", "SedziaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sedzia");
                });

            modelBuilder.Entity("Sedziowanie.Models.KomisjaCzlonek", b =>
                {
                    b.HasOne("Sedziowanie.Models.Komisja", "Komisja")
                        .WithMany("Czlonkowie")
                        .HasForeignKey("KomisjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sedziowanie.Models.Sedzia", "Sedzia")
                        .WithMany()
                        .HasForeignKey("SedziaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Komisja");

                    b.Navigation("Sedzia");
                });

            modelBuilder.Entity("Sedziowanie.Models.Mecz", b =>
                {
                    b.HasOne("Sedziowanie.Models.ApplicationUser", "GoscKlub")
                        .WithMany()
                        .HasForeignKey("GoscKlubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sedziowanie.Models.ApplicationUser", "GospodarzKlub")
                        .WithMany()
                        .HasForeignKey("GospodarzKlubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sedziowanie.Models.Rozgrywki", "Rozgrywki")
                        .WithMany("Mecze")
                        .HasForeignKey("RozgrywkiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sedziowanie.Models.Sedzia", "SedziaGlowny")
                        .WithMany("MeczeJakoSedziaGlowny")
                        .HasForeignKey("SedziaGlownyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sedziowanie.Models.Sedzia", "SedziaII")
                        .WithMany("MeczeJakoSedzia2")
                        .HasForeignKey("SedziaIIId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sedziowanie.Models.Sedzia", "SedziaI")
                        .WithMany("MeczeJakoSedzia1")
                        .HasForeignKey("SedziaIId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sedziowanie.Models.Sedzia", "SedziaLiniowyII")
                        .WithMany("MeczeJakoSedziaLiniowyII")
                        .HasForeignKey("SedziaLiniowyIIId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sedziowanie.Models.Sedzia", "SedziaLiniowyI")
                        .WithMany("MeczeJakoSedziaLiniowyI")
                        .HasForeignKey("SedziaLiniowyIId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sedziowanie.Models.Sedzia", "SedziaSekretarz")
                        .WithMany("MeczeJakoSedziaSekretarz")
                        .HasForeignKey("SedziaSekretarzId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GoscKlub");

                    b.Navigation("GospodarzKlub");

                    b.Navigation("Rozgrywki");

                    b.Navigation("SedziaGlowny");

                    b.Navigation("SedziaI");

                    b.Navigation("SedziaII");

                    b.Navigation("SedziaLiniowyI");

                    b.Navigation("SedziaLiniowyII");

                    b.Navigation("SedziaSekretarz");
                });

            modelBuilder.Entity("Sedziowanie.Models.Niedyspozycja", b =>
                {
                    b.HasOne("Sedziowanie.Models.Sedzia", "Sedzia")
                        .WithMany("Niedyspozycje")
                        .HasForeignKey("SedziaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sedzia");
                });

            modelBuilder.Entity("Sedziowanie.Models.Komisja", b =>
                {
                    b.Navigation("Czlonkowie");
                });

            modelBuilder.Entity("Sedziowanie.Models.Rozgrywki", b =>
                {
                    b.Navigation("Mecze");
                });

            modelBuilder.Entity("Sedziowanie.Models.Sedzia", b =>
                {
                    b.Navigation("MeczeJakoSedzia1");

                    b.Navigation("MeczeJakoSedzia2");

                    b.Navigation("MeczeJakoSedziaGlowny");

                    b.Navigation("MeczeJakoSedziaLiniowyI");

                    b.Navigation("MeczeJakoSedziaLiniowyII");

                    b.Navigation("MeczeJakoSedziaSekretarz");

                    b.Navigation("Niedyspozycje");
                });
#pragma warning restore 612, 618
        }
    }
}
